name: Go CI

on:
  push:
    branches: [ "workflow_and_tests" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        go-version: ['1.24.x']
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Tests
        run: go test -v -covermode=atomic ./passwordGenerator

      - name: Build bin file
        run: |
          go build -v -ldflags="-s -w" -o myapp${{ matrix.os == 'windows-latest' && '.exe' || '' }} ./...

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PassGen-${{ matrix.os }}
          path: PassGen${{ matrix.os == 'windows-latest' && '.exe' || '' }}